### ISSUE TITLE
missing jenkins state

### ISSUE THREAD

**Issue by jstrunk** [novafloss/ci-formula#19]
I like where y'all are headed with this. While reading through jenkins/master/init.sls, I saw an include for a jenkins state, but init.sls is missing. That seems to be where the jenkins packages would get installed. Is that accurate?

Thank you!
Jeff

**Comment by bersace** [comment]
Thanks for your attention :)

We depends on official jenkins-formula for base install. https://github.com/saltstack-formulas/jenkins-formula. That may need some hint or better naming. Maybe mount our formula as `jenkins.ci` or embed our own init.sls. No idea yet.

**Comment by bersace** [comment]
We also depends on nginx official formula, which is a requirement of official jenkins.nginx.

**Comment by bersace** [comment]
Here is the gitfs_remote settings :

``` yaml
gitfs_remotes:
  - https://github.com/saltstack-formulas/nginx-formula.git
  - https://github.com/saltstack-formulas/jenkins-formula.git
  - https://github.com/novafloss/ci-formula.git
```

**Comment by bersace** [comment]
Another option would be to simply fork official jenkins formula as another `jenkins-formula`.

**Comment by jstrunk** [comment]
Thank you for the clarifications.

Jeff
